// examples/example-react/src/components/InfoLink.tsx
interface InfoLinkProps {
  href: string
  children: React.ReactNode
  className?: string
}

export function InfoLink({ href, children, className = '' }: InfoLinkProps) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className={`text-indigo-500 no-underline font-medium hover:text-indigo-600 hover:underline ${className}`}
    >
      {children}
    </a>
  )
}

// examples/example-svelte/src/components/InfoLink.svelte
<script lang="ts">
  interface Props {
    href: string
    className?: string
    children?: import('svelte').Snippet
  }

  let { href, className = '', children }: Props = $props()
</script>

<a
  {href}
  target="_blank"
  rel="noreferrer"
  class="font-medium text-indigo-500 no-underline hover:text-indigo-600 hover:underline {className}"
>
  {@render children?.()}
</a>
