// examples/example-react/src/components/InfoLink.tsx
interface InfoLinkProps {
  href: string
  children: React.ReactNode
  className?: string
}

export function InfoLink({ href, children, className = '' }: InfoLinkProps) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className={`text-indigo-500 no-underline font-medium hover:text-indigo-600 hover:underline ${className}`}
    >
      {children}
    </a>
  )
}

// examples/example-vue/src/components/InfoLink.vue
<script setup lang="ts">
interface InfoLinkProps {
  href: string
  className?: string
}

defineProps<InfoLinkProps>()
</script>

<template>
  <a
    :href="href"
    target="_blank"
    rel="noreferrer"
    :class="[
      'text-indigo-500 no-underline font-medium hover:text-indigo-600 hover:underline',
      className,
    ]"
  >
    <slot />
  </a>
</template>
