// examples/example-react/src/App.tsx
import {
  FlagUs,
  FlagGb,
  FlagNo,
  FlagSe,
  FlagGr,
  FlagEu,
  FlagAqTrueSouth,
  FlagCn,
  FlagTr,
  FlagCh,
  FlagDk,
  FlagCa,
  FlagPl,
  FlagJp,
  FlagDe,
  FlagFr,
  FlagIt,
  FlagIn,
  FlagBr,
  FlagAr,
  FlagKr,
  buildMeta,
} from '@sankyu/react-circle-flags'
import type { ComponentType, SVGProps } from 'react'
import { FlagGrid } from './components/FlagGrid'
import { BuildInfoCard } from './components/BuildInfoCard'
import { createFlagGridRows, type FlagGridCode } from './libs/shared/flag-grid'

const FLAG_COMPONENTS = {
  US: FlagUs,
  GB: FlagGb,
  NO: FlagNo,
  SE: FlagSe,
  GR: FlagGr,
  EU: FlagEu,
  AQ: FlagAqTrueSouth,
  CN: FlagCn,
  TR: FlagTr,
  CH: FlagCh,
  DK: FlagDk,
  CA: FlagCa,
  PL: FlagPl,
  JP: FlagJp,
  DE: FlagDe,
  FR: FlagFr,
  IT: FlagIt,
  IN: FlagIn,
  BR: FlagBr,
  AR: FlagAr,
  KR: FlagKr,
} as const satisfies Record<FlagGridCode, ComponentType<SVGProps<SVGSVGElement>>>

const FLAG_ROWS = createFlagGridRows(code => ({
  Component: FLAG_COMPONENTS[code],
  code,
}))

const PKG_NAME = '@sankyu/react-circle-flags'

export default function App() {
  const {
    version = 'unknown',
    commitHash = 'ffffffffffffffff',
    builtTimestamp = 0,
  } = buildMeta || {}

  return (
    <div className="min-h-screen grid place-items-center bg-white font-sans text-gray-700">
      <div className="flex flex-col gap-5 items-center w-95">
        <FlagGrid rows={FLAG_ROWS} />
        <BuildInfoCard
          packageName={PKG_NAME}
          version={version}
          commitHash={commitHash}
          builtTimestamp={builtTimestamp}
        />
      </div>
    </div>
  )
}

// examples/example-svelte/src/App.svelte
<script lang="ts">
  import {
    FlagUs,
    FlagGb,
    FlagNo,
    FlagSe,
    FlagGr,
    FlagEu,
    FlagAqTrueSouth,
    FlagCn,
    FlagTr,
    FlagCh,
    FlagDk,
    FlagCa,
    FlagPl,
    FlagJp,
    FlagDe,
    FlagFr,
    FlagIt,
    FlagIn,
    FlagBr,
    FlagAr,
    FlagKr,
    buildMeta,
  } from '@sankyu/svelte-circle-flags'
  import FlagGrid from './components/FlagGrid.svelte'
  import BuildInfoCard from './components/BuildInfoCard.svelte'
  import { createFlagGridRows, type FlagGridCode } from './libs/shared/flag-grid'
  import type { Component } from 'svelte'

  const FLAG_COMPONENTS = {
    US: FlagUs,
    GB: FlagGb,
    NO: FlagNo,
    SE: FlagSe,
    GR: FlagGr,
    EU: FlagEu,
    AQ: FlagAqTrueSouth,
    CN: FlagCn,
    TR: FlagTr,
    CH: FlagCh,
    DK: FlagDk,
    CA: FlagCa,
    PL: FlagPl,
    JP: FlagJp,
    DE: FlagDe,
    FR: FlagFr,
    IT: FlagIt,
    IN: FlagIn,
    BR: FlagBr,
    AR: FlagAr,
    KR: FlagKr,
  } as const satisfies Record<FlagGridCode, Component>

  const flagRows = createFlagGridRows(code => ({
    component: FLAG_COMPONENTS[code],
    code,
  }))

  const PKG_NAME = '@sankyu/svelte-circle-flags'
  const meta = buildMeta()
</script>

<main class="min-h-screen bg-gray-50 p-6">
  <div class="mx-auto max-w-4xl space-y-8">
    <div class="text-center">
      <h1 class="mb-2 text-3xl font-bold text-gray-900">{PKG_NAME}</h1>
      <p class="text-gray-600">400+ circular SVG flags for Svelte 5</p>
    </div>

    <FlagGrid rows={flagRows} />
    <BuildInfoCard packageName={PKG_NAME} {meta} />
  </div>
</main>
